kafka:
  image: "spotify/kafka:latest"
  ports:
    - "2181:2181"
    - "9092:9092"
dynamodb:
  image: "urbanise/dynamodb-local:latest"
  ports:
    - "32000:8000"
mockApi:
  image: "parthshah/mock-admin-challenge"
  ports: 
    - "8081:8010"
submissionService:
  image: appiriodevops/ap-submission-microservice:dev.201601040301
  ports:
    - "8082:8080"
    - "8083:8081"
  links:
    - kafka:kafka
    - dynamodb:dynamodb
    - mockApi:mockApi
  environment:
    DYNAMODB_ENDPOINT: http://dynamodb:32000
    CHALLENGE_SERVICE_ENDPOINT: http://mockApi:8081/v3/
    FILE_SERVICE_ENDPOINT: http://mockApi:8081/v3/
    IDENTITY_SERVICE_ENDPOINT: http://mockApi:8081/v3/
    ZOOKEEPER_HOSTS_LIST: kafka:2181
    # CHALLENGE_SERVICE_ENDPOINT: http://${MOCKAPI_PORT_8010_TCP_ADDR}:${MOCKAPI_PORT_8010_TCP_PORT}/v3/
    # FILE_SERVICE_ENDPOINT: http://${MOCKAPI_PORT_8010_TCP_ADDR}:${MOCKAPI_PORT_8010_TCP_PORT}/v3/
    # ZOOKEEPER_HOSTS_LIST: ${KAFKA_PORT_2181_TCP_ADDR}:${KAFKA_PORT_2181_TCP_PORT}
    # IDENTITY_SERVICE_ENDPOINT: http://${MOCKAPI_PORT_8010_TCP_ADDR}:${MOCKAPI_PORT_8010_TCP_PORT}/v3/
nginx:
  build: .
  dockerfile: nginx-dockerfile
  ports:
    - "8080:80"
  links: 
    - mockApi:mockApi
    - submissionService:submissionService