kafka:
  image: "spotify/kafka:latest"
  ports:
    - "2181:2181"
    - "9092:9092"
dynamodb:
  image: "parthshah/dynamodb-local:latest"
  command: -sharedDb
  ports:
   - "32000:8000"
# dynamodb-setup: 
#   build: .
#   dockerfile: dynamodb-dockerfile
#   links:
#     # - dynamodb
#     - mockapi
mockapi:
  image: "parthshah/mock-admin-challenge"
  ports: 
    - "8081:8010"
submission-service:
  image: appiriodevops/ap-submission-microservice:dev.201601040301
  ports:
    - "8082:8080"
    - "8083:8081"
  links:
    - kafka
    - dynamodb
    # - dynamodb-setup
    - mockapi
  environment:
    DYNAMODB_ENDPOINT: http://dynamodb:32000
    CHALLENGE_SERVICE_ENDPOINT: http://mock-api:8081/v3/
    FILE_SERVICE_ENDPOINT: http://mock-api:8081/v3/
    IDENTITY_SERVICE_ENDPOINT: http://mock-api:8081/v3/
    ZOOKEEPER_HOSTS_LIST: kafka:2181
nginx:
  build: .
  dockerfile: nginx-dockerfile
  ports:
    - "8080:80"
  links: 
    - mockapi:mockapi
    # - submission-service:submission-service